### ISSUE TITLE
3.0 meta issue

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#425]
Starting this to document planned breaking changes and the like.

- [x] Decrease `stack_trace_limit` to `50` (PR: https://github.com/elastic/apm-agent-ruby/pull/515)
- [x] Remove type from exception name (https://github.com/elastic/apm-agent-ruby/pull/323)
- [x] Use `external` instead of `ext` as type (https://github.com/elastic/apm-agent-ruby/issues/473) (PR: https://github.com/elastic/apm-agent-ruby/pull/514)
- [x] Move to Monotonic durations (https://github.com/elastic/apm-agent-ruby/issues/208, PR: https://github.com/elastic/apm-agent-ruby/pull/550)
- [x] Remove to_s on label value in sidekiq spy (https://github.com/elastic/apm-agent-ruby/issues/544)
