### ISSUE TITLE
[meta][docs] Documentation restructure

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-ruby#556]
A meta issue for tracking documentation improvements outlined in https://github.com/elastic/apm-dev/issues/425.

https://github.com/elastic/apm-agent-ruby/pull/559
- [x] Top level heading and doc sync for log correlation: https://github.com/elastic/apm/issues/149
- [x] Use shared version attributes: https://github.com/elastic/apm/issues/150
- [x] Add a section on how the Agent does instrumentation: https://github.com/elastic/apm/issues/146
- [x] Rename the APM UI to "APM app": https://github.com/elastic/apm-dev/issues/567
- [x] Updates to the new documentation structure outlined [here](https://docs.google.com/spreadsheets/d/1P53LbNY7jFSLLJhOKw-nmDenQbrIFlY4EEFJGqT1kmY/edit#gid=0)
- [x] Sync Central config docs: https://github.com/elastic/apm-agent-dotnet/pull/497#discussion_r326303325

https://github.com/elastic/docs/pull/1275
- [x] Docs repo changes

https://github.com/elastic/apm-agent-ruby/pull/557
- [x] Add release notes to the documentation: https://github.com/elastic/apm/issues/132

---

**To prevent breaking the doc build, these PRs must be merged in the following order:**

1. ~https://github.com/elastic/docs/pull/1276~
2. ~https://github.com/elastic/apm-agent-ruby/pull/559, and backported to `2.x` (https://github.com/elastic/apm-agent-ruby/pull/564)~
3. ~Changes backported in the APM repo:~
```
11:05:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/get-started/7.0/agents.html:
11:05:18 INFO:build_docs:   - en/apm/agent/ruby/2.x/introduction.html#framework-support
11:05:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/get-started/7.1/agents.html:
11:05:18 INFO:build_docs:   - en/apm/agent/ruby/2.x/introduction.html#framework-support
11:05:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/get-started/7.2/agents.html:
11:05:18 INFO:build_docs:   - en/apm/agent/ruby/2.x/introduction.html#framework-support
11:05:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/get-started/7.3/agents.html:
11:05:18 INFO:build_docs:   - en/apm/agent/ruby/2.x/introduction.html#framework-support
11:05:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/get-started/7.4/agents.html:
11:05:18 INFO:build_docs:   - en/apm/agent/ruby/2.x/introduction.html#framework-support
11:05:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/get-started/current/agents.html:
11:05:18 INFO:build_docs:   - en/apm/agent/ruby/2.x/introduction.html#framework-support
11:05:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/get-started/master/agents.html:
11:05:18 INFO:build_docs:   - en/apm/agent/ruby/2.x/introduction.html#framework-support
```
4. ~https://github.com/elastic/docs/pull/1275~
5. ~https://github.com/elastic/apm-agent-ruby/pull/557, and backported to `2.x` (https://github.com/elastic/apm-agent-ruby/pull/579)~
6. ~During the next Ruby Agent release, https://github.com/elastic/docs/pull/1329 must me merged.~
